import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { RefreshCw, Bot, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function WidgetAmbientNarrative({ colors = {} }) {
  const { accentA = '#00E5FF', panel0 = '#1A1F26', panel1 = '#202833', text0 = '#E6F1FF', text1 = '#8EA0B5', muted = '#5F6E80' } = colors;

  const [events, setEvents] = useState(() => {
    try { return JSON.parse(localStorage.getItem('ambientNarrative') || '[]'); } catch { return []; }
  });
  const [loading, setLoading] = useState(false);

  const generateEvents = async () => {
    setLoading(true);
    try {
      let context = 'A superhero TTRPG campaign in NYC 2036.';
      try {
        const char = JSON.parse(localStorage.getItem('currentCharacter') || 'null');
        if (char) context += ` Active operative: ${char.name}, ${char.classification}.`;
        const campaigns = await base44.entities.Campaign.list('-updated_date', 1);
        if (campaigns[0]) context += ` Campaign: ${campaigns[0].name}. Status: ${campaigns[0].status}.`;
      } catch {}

      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `You are the world's narrator for a superhero TTRPG set in NYC 2036.
Context: ${context}

Generate 3 short "world event" dispatches — things happening RIGHT NOW in the city that operatives might notice or be affected by. Each should be 1-2 sentences, written like a news ticker or intercepted comms signal. Make them feel alive and urgent.

Return JSON.`,
        response_json_schema: {
          type: 'object',
          properties: {
            events: {
              type: 'array',
              items: { type: 'string' }
            }
          }
        }
      });

      const newEvents = (result.events || []).slice(0, 3);
      setEvents(newEvents);
      localStorage.setItem('ambientNarrative', JSON.stringify(newEvents));
    } catch {
      setEvents(['// SIGNAL LOST — RECONNECTING TO WORLD FEED...']);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (events.length === 0) generateEvents();
  }, []);

  return (
    <div className="rounded-xl border overflow-hidden" style={{ background: panel0, borderColor: accentA + '20' }}>
      <div className="flex items-center justify-between px-4 py-3 border-b" style={{ borderColor: accentA + '15' }}>
        <div className="flex items-center gap-2">
          <Bot className="h-3.5 w-3.5" style={{ color: 'rgba(167,139,250,0.9)' }} />
          <span className="text-[10px] font-mono font-bold tracking-widest uppercase" style={{ color: text0 }}>
            A.I. World Feed
          </span>
        </div>
        <button onClick={generateEvents} disabled={loading}
          className="p-1 rounded hover:opacity-70 transition-all disabled:opacity-40">
          <RefreshCw className={`h-3 w-3 ${loading ? 'animate-spin' : ''}`} style={{ color: muted }} />
        </button>
      </div>

      <div className="p-3 space-y-2 min-h-[80px]">
        <AnimatePresence mode="wait">
          {loading ? (
            <motion.div key="loading" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="flex items-center justify-center py-6 gap-2">
              <Loader2 className="h-4 w-4 animate-spin" style={{ color: 'rgba(167,139,250,0.7)' }} />
              <span className="text-[10px] font-mono" style={{ color: muted }}>Scanning world state...</span>
            </motion.div>
          ) : events.length > 0 ? (
            <motion.div key="events" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="space-y-2">
              {events.map((evt, i) => (
                <div key={i} className="flex items-start gap-2 py-1.5 border-b last:border-0"
                  style={{ borderColor: accentA + '10' }}>
                  <span className="text-[9px] font-mono mt-0.5 flex-shrink-0" style={{ color: 'rgba(167,139,250,0.6)' }}>
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <p className="text-[10px] leading-relaxed" style={{ color: text1 }}>{evt}</p>
                </div>
              ))}
              <p className="text-[8px] font-mono text-right" style={{ color: muted }}>
                Generated by A.I. Director • Tap ↺ to refresh
              </p>
            </motion.div>
          ) : null}
        </AnimatePresence>
      </div>
    </div>
  );
}